'use client';
import {useEffect,useState,type FormEvent} from 'react';
import Link from 'next/link';
import {requestJson,errorMessage} from '@/lib/client-api';
type Admin={id:string;username:string;is_master:boolean};
export default function Manage(){const [admins,setAdmins]=useState<Admin[]>([]);const [error,setError]=useState('');const [message,setMessage]=useState('');const [busy,setBusy]=useState(false);const [target,setTarget]=useState<Admin|null>(null);
 useEffect(()=>{requestJson<Admin[]>('/api/admin/manage').then(setAdmins).catch(e=>setError(errorMessage(e)));},[]);
 async function create(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget;setBusy(true);setError('');setMessage('');try{await requestJson('/api/admin/manage',Object.fromEntries(new FormData(form)));setAdmins(await requestJson<Admin[]>('/api/admin/manage'));form.reset();setMessage('Administrator created.');}catch(e){setError(errorMessage(e));}finally{setBusy(false);}}
 async function remove(admin:Admin){if(!confirm(`Remove ${admin.username}? Their sessions will be revoked.`))return;setBusy(true);setError('');setMessage('');try{await requestJson('/api/admin/manage',{id:admin.id},'DELETE');setAdmins(a=>a.filter(x=>x.id!==admin.id));setMessage('Administrator removed.');}catch(e){setError(errorMessage(e));}finally{setBusy(false);}}
 async function reset(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!target)return;setBusy(true);setError('');setMessage('');try{await requestJson('/api/admin/manage/reset-password',{id:target.id,new_password:new FormData(e.currentTarget).get('new_password')});setTarget(null);setMessage('Password reset. All sessions for that administrator were revoked.');}catch(e){setError(errorMessage(e));}finally{setBusy(false);}}
 return <main className="portal-page space-y-6"><Link href="/account" className="underline">Back to my account</Link><h1 className="text-2xl font-bold">Manage administrators</h1>{error&&<p role="alert" className="text-red-700">{error}</p>}{message&&<p role="status">{message}</p>}<section className="portal-card space-y-4">{admins.map(a=><article className="flex flex-wrap items-center justify-between gap-3 border-b pb-3" key={a.id}><span>{a.username}{a.is_master?' (Master)':''}</span>{!a.is_master&&<div className="flex gap-2"><button className="portal-button secondary" disabled={busy} onClick={()=>setTarget(a)}>Reset password</button><button className="portal-button secondary" disabled={busy} onClick={()=>remove(a)}>Remove</button></div>}</article>)}</section>
 <section className="portal-card"><h2 className="mb-4 text-lg font-semibold">Create administrator</h2><form onSubmit={create} className="space-y-3"><label className="portal-field">Username<input className="portal-input" name="username" required minLength={3} maxLength={80} pattern="[a-zA-Z0-9_.@-]+" autoComplete="off"/></label><label className="portal-field">Password (12-72 characters)<input className="portal-input" type="password" name="password" required minLength={12} maxLength={72} autoComplete="new-password"/></label><button className="portal-button" disabled={busy}>Create administrator</button></form></section>
 {target&&<section className="portal-card"><h2 className="mb-4 text-lg font-semibold">Reset password for {target.username}</h2><form onSubmit={reset} className="space-y-3"><label className="portal-field">New password<input className="portal-input" type="password" name="new_password" required minLength={12} maxLength={72} autoComplete="new-password"/></label><button className="portal-button" disabled={busy}>Reset password</button><button type="button" className="portal-button secondary ml-3" onClick={()=>setTarget(null)}>Cancel</button></form></section>}</main>;}
