'use client';
import { useEffect, useState } from 'react';
import { requestJson, errorMessage } from '@/lib/client-api';
type Report = { date: string; page: number; page_size: number; total: number; stats: { total_registered: number; total_checked_in: number; attendance_percentage: number; role_breakdown: Record<string,number> }; participants: {id:string;full_name:string;organization:string;role:string;attendance_status:string;check_in_time:string|null}[] };
export default function Attendance() {
  const [data,setData]=useState<Report|null>(null); const [error,setError]=useState(''); const [name,setName]=useState(''); const [organization,setOrganization]=useState(''); const [role,setRole]=useState(''); const [status,setStatus]=useState(''); const [date,setDate]=useState(''); const [page,setPage]=useState(1); const [refresh,setRefresh]=useState(0);
  useEffect(() => {
    let active=true;
    const load=async () => { try { const query=new URLSearchParams({name,organization,page:String(page)}); if(role)query.set('role',role);if(status)query.set('status',status);if(date)query.set('date',date); const report=await requestJson<Report>('/api/attendance?'+query);if(active){setData(report);setError('');} } catch(e){if(active)setError(errorMessage(e));} };
    const timeout=setTimeout(load,200);const timer=setInterval(()=>{if(!document.hidden)void load();},15000);
    return()=>{active=false;clearTimeout(timeout);clearInterval(timer);};
  },[name,organization,role,status,date,page,refresh]);
  return <main className="portal-page"><h1 className="mb-2 text-2xl font-bold">Attendance</h1><p className="mb-6">Daily check-ins | Harare time</p>{error&&<p role="alert" className="mb-4 text-red-700">{error}</p>}
    {data&&<><div className="mb-6 grid grid-cols-3 gap-3">{[[data.stats.total_registered,'Registered'],[data.stats.total_checked_in,'Checked in'],[`${data.stats.attendance_percentage}%`,'Attendance']].map(([value,label])=><div className="portal-card p-3 text-center" key={label}><strong className="text-xl">{value}</strong><p className="text-xs">{label}</p></div>)}</div><p className="mb-4 text-sm">Showing {data.date}. {data.stats.total_registered-data.stats.total_checked_in} not checked in. Entry QR codes are issued to Partners.</p><div className="mb-6 flex flex-wrap gap-2">{Object.entries(data.stats.role_breakdown).map(([label,count])=><span className="rounded-lg bg-white px-3 py-2 text-xs" key={label}>{label}: {count}</span>)}</div></>}
    <section className="portal-card space-y-4"><div className="grid gap-3 sm:grid-cols-2"><label className="portal-field">Search name<input className="portal-input" value={name} maxLength={160} onChange={e=>{setName(e.target.value);setPage(1);}}/></label><label className="portal-field">Search organization<input className="portal-input" value={organization} maxLength={160} onChange={e=>{setOrganization(e.target.value);setPage(1);}}/></label><label className="portal-field">Date<input className="portal-input" type="date" value={date} onChange={e=>{setDate(e.target.value);setPage(1);}}/></label><label className="portal-field">Role<select className="portal-input" value={role} onChange={e=>{setRole(e.target.value);setPage(1);}}><option value="">All roles</option>{['Partner','OAK Staff','Coordination Team','Presenter','Observer'].map(r=><option key={r}>{r}</option>)}</select></label><label className="portal-field">Status<select className="portal-input" value={status} onChange={e=>{setStatus(e.target.value);setPage(1);}}><option value="">All statuses</option><option value="checked_in">Checked in</option><option value="pending">Pending</option></select></label></div><button className="portal-button secondary" onClick={()=>setRefresh(n=>n+1)}>Refresh</button>
    {!data&&!error&&<p role="status">Loading attendance...</p>}{data?.participants.map(p=><article className="border-t border-slate-100 py-4" key={p.id}><div className="flex justify-between gap-4"><strong>{p.full_name}</strong><span>{p.attendance_status==='checked_in'?'Present':'Pending'}</span></div><p className="text-sm">{p.organization} | {p.role}</p>{p.check_in_time&&<time className="text-xs">{new Date(p.check_in_time).toLocaleString('en-GB',{timeZone:'Africa/Harare'})}</time>}</article>)}{data?.participants.length===0&&<p>No participants match these filters.</p>}
    {data&&<div className="flex items-center justify-between gap-3"><button className="portal-button secondary" disabled={page===1} onClick={()=>setPage(p=>p-1)}>Previous</button><span className="text-sm">Page {page} | {data.total} results</span><button className="portal-button secondary" disabled={page*data.page_size>=data.total} onClick={()=>setPage(p=>p+1)}>Next</button></div>}</section></main>;
}
