'use client';
import { useCallback,useEffect,useRef,useState } from 'react';
import type { Html5Qrcode } from 'html5-qrcode';
import { requestJson,errorMessage } from '@/lib/client-api';
type Result={participant:{first_name:string;last_name:string;organization:string};already:boolean;check_in_time:string;live_stats:{total_registered:number;total_checked_in:number}};
export default function CheckIn(){
 const [code,setCode]=useState('');const [error,setError]=useState('');const [result,setResult]=useState<Result|null>(null);const [busy,setBusy]=useState(false);const [camera,setCamera]=useState(false);
 const scanner=useRef<Html5Qrcode|null>(null);const locked=useRef(false);const generation=useRef(0);const alive=useRef(true);
 const stop=useCallback(async()=>{generation.current++;const current=scanner.current;scanner.current=null;if(current){try{if(current.isScanning)await current.stop();current.clear();}catch{}}if(alive.current)setCamera(false);},[]);
 useEffect(()=>{alive.current=true;return()=>{alive.current=false;void stop();};},[stop]);
 async function submit(value:string){if(locked.current||!value.trim())return;locked.current=true;setBusy(true);setError('');await stop();try{const data=await requestJson<Result>('/api/checkin',{qr_code_id:value.trim()});if(alive.current){setResult(data);setCode('');}}catch(e){if(alive.current)setError(errorMessage(e));}finally{locked.current=false;if(alive.current)setBusy(false);}}
 async function start(){setError('');const attempt=++generation.current;setCamera(true);try{const {Html5Qrcode}=await import('html5-qrcode');if(attempt!==generation.current)return;const reader=new Html5Qrcode('qr-reader');scanner.current=reader;await reader.start({facingMode:'environment'},{fps:10,qrbox:{width:240,height:240}},value=>{void submit(value);},()=>{});if(attempt!==generation.current){if(reader.isScanning)await reader.stop();reader.clear();}}catch{if(attempt===generation.current){await stop();setError('Camera unavailable. Allow camera access over HTTPS, or enter the pass code below.');}}}
 return <main className="portal-page"><h1 className="mb-2 text-2xl font-bold">Event check-in</h1><p className="mb-6">Scan a Partner entry pass. Check-ins are recorded per day in Harare time.</p>{error&&<p role="alert" className="mb-4 text-red-700">{error}</p>}{result&&<section className="portal-card mb-6 space-y-3 border-green-200"><h2 className="text-xl font-semibold text-green-800">{result.already?'Already checked in today':'Checked in successfully'}</h2><p>{result.participant.first_name} {result.participant.last_name}</p><p>{result.participant.organization}</p><p>Original check-in: {new Date(result.check_in_time).toLocaleString('en-GB',{timeZone:'Africa/Harare'})}</p><p>{result.live_stats.total_checked_in} of {result.live_stats.total_registered} participants checked in today.</p><button className="portal-button" onClick={()=>{setResult(null);setError('');}}>Scan next attendee</button></section>}
 <section className="portal-card space-y-4"><div id="qr-reader" className="min-h-32 w-full overflow-hidden rounded-xl bg-slate-100"/><button className="portal-button" disabled={busy} onClick={()=>camera?void stop():void start()}>{camera?'Stop camera':'Start camera'}</button><form onSubmit={e=>{e.preventDefault();void submit(code);}} className="space-y-3"><label className="portal-field">Manual pass code<input className="portal-input" value={code} onChange={e=>setCode(e.target.value)} required maxLength={80} autoComplete="off" placeholder="OAK-2026-..."/></label><button className="portal-button" disabled={busy||!code.trim()}>{busy?'Checking...':'Check in'}</button></form></section></main>;
}
