'use client';
import {useEffect,useState,type FormEvent} from 'react';
import Link from 'next/link';
import {useRouter} from 'next/navigation';
import {requestJson,errorMessage} from '@/lib/client-api';
type Admin={username:string;is_master:boolean};
export default function Account(){const router=useRouter();const [admin,setAdmin]=useState<Admin|null>(null);const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [recovery,setRecovery]=useState('');
 useEffect(()=>{requestJson<Admin>('/api/admin/me').then(setAdmin).catch(e=>setError(errorMessage(e)));},[]);
 async function change(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);if(f.get('new_password')!==f.get('confirm_password')){setError('New passwords do not match.');return;}setBusy(true);setError('');try{await requestJson('/api/admin/change-password',Object.fromEntries(f));router.push('/admin-login');router.refresh();}catch(e){setError(errorMessage(e));}finally{setBusy(false);}}
 async function recover(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError('');setRecovery('');try{const d=await requestJson<{recovery_code:string}>('/api/admin/recover-participant',Object.fromEntries(new FormData(e.currentTarget)));setRecovery(d.recovery_code);}catch(e){setError(errorMessage(e));}finally{setBusy(false);}}
 return <main className="portal-page space-y-6"><h1 className="text-2xl font-bold">My account</h1>{error&&<p role="alert" className="text-red-700">{error}</p>}{admin&&<section className="portal-card"><h2 className="text-xl font-semibold">{admin.username}</h2><p>{admin.is_master?'Master administrator':'Administrator'}</p><p className="mt-3 text-sm">Sessions expire after 8 hours. Changing your password signs out all sessions.</p>{admin.is_master&&<Link href="/account/manage-admins" className="portal-button mt-5 inline-block">Manage administrators</Link>}</section>}
 <section className="portal-card"><h2 className="mb-4 text-xl font-semibold">Change password</h2><form onSubmit={change} className="space-y-4">{[['current_password','Current password'],['new_password','New password'],['confirm_password','Confirm new password']].map(([name,label])=><label key={name} className="portal-field">{label}<input className="portal-input" name={name} type="password" required minLength={name==='current_password'?1:12} maxLength={72} autoComplete={name==='current_password'?'current-password':'new-password'}/></label>)}<p className="text-sm">Use at least 12 characters. You will need to sign in again.</p><button className="portal-button" disabled={busy}>Change password</button></form></section>
 <section className="portal-card"><h2 className="mb-4 text-xl font-semibold">Participant account recovery</h2><p className="mb-4 text-sm">Verify the participant?s identity before issuing a replacement code. Existing participant sessions will be signed out.</p><form onSubmit={recover} className="space-y-3"><label className="portal-field">Registration ID<input className="portal-input" name="registration_id" required maxLength={100}/></label><label className="portal-field">Registered email<input className="portal-input" name="email" type="email" required maxLength={254}/></label><button className="portal-button" disabled={busy}>Issue replacement recovery code</button></form>{recovery&&<p role="status" className="mt-4 break-all rounded-xl bg-slate-100 p-4 font-mono text-sm">{recovery}</p>}</section></main>;}
